
/* This file was generated by idltool 53.24. Do not edit */

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif
#ifndef LIBRARIES_UTF8_H
#include <libraries/UTF8.h>
#endif

/* forward declaration */
struct UTF8IFace;

extern ULONG                VARARGS68K _UTF8_Obtain(struct UTF8IFace *);
extern ULONG                VARARGS68K _UTF8_Release(struct UTF8IFace *);
extern int                  VARARGS68K _UTF8_UTF8CaseCmp(struct UTF8IFace *, unsigned char * UTF8_alphabet, unsigned char * UTF8_one, unsigned char * UTF8_two);
extern int                  VARARGS68K _UTF8_UTF8Cmp(struct UTF8IFace *, unsigned char * UTF8_alphabet, unsigned char * UTF8_one, unsigned char * UTF8_two);
extern char *               VARARGS68K _UTF8_UTF8Decode(struct UTF8IFace *, ULONG * codeset_page, unsigned char * UTF8, ULONG flags);
extern char *               VARARGS68K _UTF8_UTF8DecodeLen(struct UTF8IFace *, ULONG * codeset_page, unsigned char * UTF8, ULONG len, ULONG flags);
extern unsigned char *      VARARGS68K _UTF8_UTF8Encode(struct UTF8IFace *, ULONG * codeset_page, char * ascii, ULONG flags);
extern int                  VARARGS68K _UTF8_UTF8EstimateByteSize(struct UTF8IFace *, ULONG glyph);
extern ULONG                VARARGS68K _UTF8_UTF8FindGlyph(struct UTF8IFace *, unsigned char * UTF8_alphabet, ULONG glyph);
extern ULONG                VARARGS68K _UTF8_UTF8GetGlyph(struct UTF8IFace *, unsigned char * UTF8, int * len);
extern ULONG                VARARGS68K _UTF8_UTF8GetGlyphAt(struct UTF8IFace *, unsigned char * UTF8, int pos, int * len);
extern ULONG                VARARGS68K _UTF8_UTF8GetOffsetSize(struct UTF8IFace *, unsigned char * UTF8, int to_pos);
extern ULONG                VARARGS68K _UTF8_UTF8GetSize(struct UTF8IFace *, unsigned char * UTF8);
extern int                  VARARGS68K _UTF8_UTF8IndexOf(struct UTF8IFace *, unsigned char * UTF8, unsigned char * find);
extern unsigned char *      VARARGS68K _UTF8_UTF8Insert(struct UTF8IFace *, unsigned char * UTF8, int start, unsigned char * UTF8_insert, ULONG mem_flags);
extern unsigned char *      VARARGS68K _UTF8_UTF8Left(struct UTF8IFace *, unsigned char * UTF8, int len, ULONG mem_flags);
extern ULONG                VARARGS68K _UTF8_UTF8Length(struct UTF8IFace *, unsigned char * UTF8);
extern unsigned char *      VARARGS68K _UTF8_UTF8Merge(struct UTF8IFace *, ULONG mem_flags,  ...);
extern BOOL                 VARARGS68K _UTF8_UTF8ModInsert(struct UTF8IFace *, unsigned char ** UTF8, int start, unsigned char * UTF8_insert, ULONG mem_flags);
extern BOOL                 VARARGS68K _UTF8_UTF8ModLeft(struct UTF8IFace *, unsigned char ** UTF8, int len, ULONG mem_flags);
extern BOOL                 VARARGS68K _UTF8_UTF8ModRemove(struct UTF8IFace *, unsigned char ** UTF8, int start, int len, ULONG mem_flags);
extern BOOL                 VARARGS68K _UTF8_UTF8ModRight(struct UTF8IFace *, unsigned char ** UTF8, int len, ULONG mem_flags);
extern BOOL                 VARARGS68K _UTF8_UTF8ModSubString(struct UTF8IFace *, unsigned char ** UTF8, int start, int len, ULONG mem_flags);
extern BOOL                 VARARGS68K _UTF8_UTF8ModToLower(struct UTF8IFace *, unsigned char * alphabet_UTF8, unsigned char ** UTF8, ULONG mem_flags);
extern BOOL                 VARARGS68K _UTF8_UTF8ModToUpper(struct UTF8IFace *, unsigned char * alphabet_UTF8, unsigned char ** UTF8, ULONG mem_flags);
extern BOOL                 VARARGS68K _UTF8_UTF8ModTrim(struct UTF8IFace *, unsigned char ** UTF8, ULONG mem_flags);
extern void                 VARARGS68K _UTF8_UTF8Printf(struct UTF8IFace *, ULONG * codeset_page, unsigned char * utf8_fmt,  ...);
extern unsigned char *      VARARGS68K _UTF8_UTF8Remove(struct UTF8IFace *, unsigned char * UTF8, int start, int len, ULONG mem_flags);
extern unsigned char *      VARARGS68K _UTF8_UTF8Right(struct UTF8IFace *, unsigned char * UTF8, int len, ULONG mem_flags);
extern ULONG                VARARGS68K _UTF8_UTF8SetGlyph(struct UTF8IFace *, ULONG glyph, unsigned char * data);
extern unsigned char *      VARARGS68K _UTF8_UTF8SubString(struct UTF8IFace *, unsigned char * UTF8, int start, int len, ULONG mem_flags);
extern unsigned char *      VARARGS68K _UTF8_UTF8ToLower(struct UTF8IFace *, unsigned char * alphabet_UTF8, unsigned char * UTF8, ULONG mem_flags);
extern unsigned char *      VARARGS68K _UTF8_UTF8ToUpper(struct UTF8IFace *, unsigned char * alphabet_UTF8, unsigned char * UTF8, ULONG mem_flags);
extern unsigned char *      VARARGS68K _UTF8_UTF8Trim(struct UTF8IFace *, unsigned char * UTF8, ULONG mem_flags);
extern void                 VARARGS68K _UTF8_UTF8TextExtent(struct UTF8IFace *, struct OutlineFont * ofont, float font_size, unsigned char * UTF8, struct TextExtent * ext);
extern void                 VARARGS68K _UTF8_UTF8TextExtentN(struct UTF8IFace *, struct OutlineFont * ofont, float font_size, unsigned char * UTF8, int n, struct TextExtent * ext);
extern int                  VARARGS68K _UTF8_UTF8TextLength(struct UTF8IFace *, struct OutlineFont * ofont, float font_size, unsigned char * UTF8);
extern int                  VARARGS68K _UTF8_UTF8TextLengthN(struct UTF8IFace *, struct OutlineFont * ofont, float font_size, unsigned char * UTF8, int n);
extern void                 VARARGS68K _UTF8_UTF8Text(struct UTF8IFace *, struct RastPort * rp, struct OutlineFont * ofont, float font_size, int xpos, int ypos, unsigned char * UTF8);
extern void                 VARARGS68K _UTF8_UTF8TextN(struct UTF8IFace *, struct RastPort * rp, struct OutlineFont * ofont, float font_size, int xpos, int ypos, unsigned char * UTF8, int n);
extern void                 VARARGS68K _UTF8_UTF32Text(struct UTF8IFace *, struct RastPort * rp, struct OutlineFont * ofont, float font_size, int xpos, int ypos, ULONG * UTF32);
