
/* This file was generated by idltool 53.24. Do not edit */

#include "UTF8_vectors.h"

STATIC uint32 VARARGS68K _UTF8_UNIMPLEMENTED(struct UTF8IFace *iface UNUSED)
{
  return 0;
}
STATIC CONST APTR main_v1_vectors[] =
{
    _UTF8_Obtain,
    _UTF8_Release,
    _UTF8_UNIMPLEMENTED, /* Expunge */
    _UTF8_UNIMPLEMENTED, /* Clone */
    _UTF8_UTF8CaseCmp,
    _UTF8_UTF8Cmp,
    _UTF8_UTF8Decode,
    _UTF8_UTF8DecodeLen,
    _UTF8_UTF8Encode,
    _UTF8_UTF8EstimateByteSize,
    _UTF8_UTF8FindGlyph,
    _UTF8_UTF8GetGlyph,
    _UTF8_UTF8GetGlyphAt,
    _UTF8_UTF8GetOffsetSize,
    _UTF8_UTF8GetSize,
    _UTF8_UTF8IndexOf,
    _UTF8_UTF8Insert,
    _UTF8_UTF8Left,
    _UTF8_UTF8Length,
    _UTF8_UTF8Merge,
    _UTF8_UTF8ModInsert,
    _UTF8_UTF8ModLeft,
    _UTF8_UTF8ModRemove,
    _UTF8_UTF8ModRight,
    _UTF8_UTF8ModSubString,
    _UTF8_UTF8ModToLower,
    _UTF8_UTF8ModToUpper,
    _UTF8_UTF8ModTrim,
    _UTF8_UTF8Printf,
    _UTF8_UTF8Remove,
    _UTF8_UTF8Right,
    _UTF8_UTF8SetGlyph,
    _UTF8_UTF8SubString,
    _UTF8_UTF8ToLower,
    _UTF8_UTF8ToUpper,
    _UTF8_UTF8Trim,
    _UTF8_UTF8TextExtent,
    _UTF8_UTF8TextExtentN,
    _UTF8_UTF8TextLength,
    _UTF8_UTF8TextLengthN,
    _UTF8_UTF8Text,
    _UTF8_UTF8TextN,
    _UTF8_UTF32Text,
    (APTR)-1
};
