
/* This file was generated by idltool 53.1. Do not edit */

#ifndef EXEC_TYPES_H
#include <exec/types.h>

#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef LIBRARIES_UTF8_H
#include <libraries/UTF8.h>
#endif

extern ULONG			_UTF8_Obtain(struct UTF8IFace *);
extern ULONG			_UTF8_Release(struct UTF8IFace *);

extern int				_UTF8_CaseCmp(struct UTF8IFace *Self, unsigned char *UTF8_alphabet, unsigned char *UTF8_one,  unsigned char *UTF8_two);
extern int				_UTF8_Cmp(struct UTF8IFace *Self, unsigned char *UTF8_alphabet, unsigned char *UTF8_one,  unsigned char *UTF8_two);

extern unsigned char *	_UTF8_Copy(struct UTF8IFace *Self, ULONG mem_flags );
extern char *			_UTF8_Decode(struct UTF8IFace *Self, ULONG *codeset_page, unsigned char * UTF8, ULONG flags );

extern char *			_UTF8_DecodeLen(struct UTF8IFace *Self, ULONG *codeset_page, unsigned char * UTF8, ULONG bytes, ULONG flags );

extern unsigned char *	_UTF8_Encode(struct UTF8IFace *Self, ULONG *codeset_page, char * ascii, ULONG mem_flags);
extern int				_UTF8_EstimateByteSize(struct UTF8IFace *, ULONG glyph);

extern ULONG			_UTF8_FindGlyph( struct UTF8IFace *, unsigned char *UTF8_alphabet, ULONG value_one );

extern ULONG			_UTF8_GetGlyph(struct UTF8IFace *, unsigned char *data, int *len);
extern ULONG			_UTF8_GetGlyphAt(struct UTF8IFace *, unsigned char *data, int pos, int *len);
extern ULONG           		_UTF8_GetOffsetSize(struct UTF8IFace *, unsigned char * UTF8, int to_pos);
extern ULONG           		_UTF8_GetSize(struct UTF8IFace *self, unsigned char *UTF8);
extern int				_UTF8_IndexOf (struct UTF8IFace *Self, unsigned char * utf8,unsigned char *find);
extern unsigned char *	_UTF8_Insert (struct UTF8IFace *Self,unsigned char *UTF8, int _start, unsigned char *UTF8_insert , ULONG flags );
extern unsigned char *	_UTF8_Left (struct UTF8IFace *Self, unsigned char *UTF8, int _len, ULONG mem_flags );
extern ULONG			_UTF8_Length(struct UTF8IFace *Self,unsigned char * UTF8);
extern unsigned char *	VARARGS68K _UTF8_Merge (struct UTF8IFace *Self, ULONG mem_flags, ... );
extern BOOL			_UTF8_ModInsert(struct UTF8IFace *Self, unsigned char **UTF8, int _start, unsigned char *UTF8_insert , ULONG flags );
extern BOOL			_UTF8_ModLeft (struct UTF8IFace *Self, unsigned char *UTF8, int _len, ULONG mem_flags );
extern BOOL			_UTF8_ModRemove(struct UTF8IFace *Self,	unsigned char **UTF8, int _start, int _len, ULONG flags );
extern BOOL			_UTF8_ModRight ( unsigned char *UTF8, int _len, ULONG mem_flags );
extern BOOL			_UTF8_ModSubString(struct UTF8IFace *Self,unsigned char **UTF8, int _start, int _len, ULONG flags );
extern BOOL			_UTF8_ModToLower(struct UTF8IFace *, unsigned char **UTF8,unsigned char *alphabet_UTF8, ULONG mem_flags);
extern BOOL			_UTF8_ModToUpper(struct UTF8IFace *, unsigned char **UTF8,unsigned char *alphabet_UTF8, ULONG mem_flags);
extern BOOL			_UTF8_ModTrim(struct UTF8IFace *Self, unsigned char **UTF8, ULONG mem_flags );
extern void 			VARARGS68K _UTF8_Printf (struct UTF8IFace *Self,ULONG *codeset_page, unsigned char *utf8_fmt, ...);
extern unsigned char *	_UTF8_Remove(struct UTF8IFace *Self,unsigned char *UTF8, int _start, int _len, ULONG flags );
extern unsigned char *	_UTF8_Right ( struct UTF8IFace *Self, unsigned char *UTF8, int _len, ULONG mem_flags );
extern ULONG			_UTF8_SetGlyph(struct UTF8IFace *, ULONG glyph, unsigned char * data);
extern unsigned char *	_UTF8_SubString(struct UTF8IFace *Self,	unsigned char *UTF8, int _start, int _len, ULONG mem_flags );
extern unsigned char *	_UTF8_ToLower(struct UTF8IFace *, unsigned char *alphabet_UTF8, unsigned char * UTF8, ULONG mem_flags);
extern unsigned char *	_UTF8_ToUpper(struct UTF8IFace *, unsigned char *alphabet_UTF8, unsigned char * UTF8, ULONG mem_flags);
extern unsigned char *	_UTF8_Trim(struct UTF8IFace *Self, unsigned char *UTF8, ULONG mem_flags );

extern void _UTF8_TextUTF8Extent( struct UTF8IFace *Self,struct OutlineFont *ofont, float font_size, unsigned char *UTF8, struct TextExtent *ext );
extern void _UTF8_TextUTF8ExtentN( struct UTF8IFace *Self,struct OutlineFont *ofont, float font_size, unsigned char *UTF8, struct TextExtent *ext, int n );
extern int _UTF8_TextUTF8Length( struct UTF8IFace *Self,struct OutlineFont *ofont, float font_size, unsigned char *UTF8 );
extern int _UTF8_TextUTF8LengthN( struct UTF8IFace *Self,struct OutlineFont *ofont, float font_size, unsigned char *UTF8, int n );
extern void _UTF8_TextUTF8( struct UTF8IFace *Self,struct RastPort *rp,struct OutlineFont *ofont, float font_size, int xpos, int ypos, unsigned char *UTF8 );
extern void _UTF8_TextUTF8N( struct UTF8IFace *Self,struct RastPort *rp,struct OutlineFont *ofont, float font_size, int xpos, int ypos, unsigned char *UTF8, int n );
extern void _UTF32_TextUTF32( struct UTF8IFace *Self,struct RastPort *rp,struct OutlineFont *ofont, float font_size, int xpos, int ypos, ULONG *UTF32 );

